### ISSUE TITLE
Error while installing on webpack-helpers

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/just-the-hm-docs#10]
**Describe the bug**

@joeleenk I merged your pull request humanmade/webpack-helpers#210, and the build action is failing with this error:

```
Configuration file: /github/workspace/./docs/_config.yml
             Theme: just-the-hm-docs
github-pages 228 | Error:  The just-the-hm-docs theme could not be found.
```

[Action build log available here](https://github.com/humanmade/webpack-helpers/actions/runs/4125578494/jobs/7126321035)

We've published the latest version, [I see it on rubygems](https://rubygems.org/gems/just-the-hm-docs), so I'm not sure what the issue is here 🤔

**Comment by joeleenk** [comment]
Hmm, the build for asset loader worked. The only real differences I see are the use of the GitHub action (instead of publishing the branch) and in the Gemfile, Webpack Helpers has `gem 'github-pages', group: :jekyll_plugins`, which I'm not sure is necessary anymore?

Otherwise, could it be a versioning thing or that we need to install the gem, since it was using a different theme previously?

**Comment by goldenapples** [comment]
It looks like the [jekyll-build-pages action](https://github.com/actions/jekyll-build-pages) doesn't run a bundle install in the source directory, so you probably can't use gem themes with it. 

I wonder if we could use the `remote_theme` syntax to pull the theme directly from the github repo?

**Comment by joeleenk** [comment]
Closing this as we solved the problem by using the GitHub Actions workflow for build & deploy.
